# QAMO 3040: First steps

In [1]:
import numpy as np

In [3]:
np.random.seed(1)

In [5]:
e = np.random.randint(0, 20, 15)

In [6]:
e

array([18,  5, 18, 11, 10, 14, 18,  4,  9, 17,  0, 13,  9,  9,  7])

In [7]:
e[5]

14

In [8]:
x = np.arange(20, 101, 20)

In [9]:
x

array([ 20,  40,  60,  80, 100])

In [10]:
print(np.power(x, 2))

[  400  1600  3600  6400 10000]


In [12]:
print(np.power(x, 0.5))

[ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]


In [13]:
print(np.log(x))

[2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]


In [14]:
print(np.exp(x))

[4.85165195e+08 2.35385267e+17 1.14200739e+26 5.54062238e+34
 2.68811714e+43]


In [15]:
print(np.power(x, 2))
print(np.power(x, 0.5))
print(np.log(x))
print(np.exp(x))

[  400  1600  3600  6400 10000]
[ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
[2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
[4.85165195e+08 2.35385267e+17 1.14200739e+26 5.54062238e+34
 2.68811714e+43]


In [16]:
x_new = [[x>50]]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
x_new = np.where(x > 50)

In [26]:
x_new

(array([2, 3, 4], dtype=int64),)

## Pandas

In [ ]:
python -m venv venv

In [ ]:
venv\Scripts\activate

In [ ]:
pip install --user ipykernel

In [ ]:
python -m ipykernel --user --name=venv